// Fill out your copyright notice in the Description page of Project Settings.


#include "Player/ActionCharacter.h"
#include "EnhancedInputComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "Camera/CameraComponent.h"
#include "Player/ResourceComponent.h"
#include "Kismet/KismetMathLibrary.h"

// Sets default values
AActionCharacter::AActionCharacter()
{
	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	SpringArm = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArm->SetupAttachment(RootComponent);
	SpringArm->TargetArmLength = 350.0f;
	SpringArm->SocketOffset = FVector(0, 0, 250);
	SpringArm->bUsePawnControlRotation = true; // 스프링암의 회전을 컨트롤러에 맞춤

	PlayerCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("PlayerCamera"));
	PlayerCamera->SetupAttachment(SpringArm);
	PlayerCamera->SetRelativeRotation(FRotator(-20.0f, 0.0f, 0.0f));

	bUseControllerRotationYaw = false; // 컨트롤러의 Yaw 회전을 사용함 -> 컨트롤러의 Yaw 회전을 캐릭터에 적용

	GetCharacterMovement()->bOrientRotationToMovement = true; // 이동 방향을 바라보게 회전
	GetCharacterMovement()->RotationRate = FRotator(0, 360, 0);

	Resource = CreateDefaultSubobject<UResourceComponent>(TEXT("PlayerReource"));
}

// Called when the game starts or when spawned
void AActionCharacter::BeginPlay()
{
	Super::BeginPlay();
	if (GetMesh()) AnimInstance = GetMesh()->GetAnimInstance();
	if (Resource) Resource->OnStaminaEmpty.AddDynamic(this, &AActionCharacter::SetWalkMode);
}

// Called every frame
void AActionCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (IsSprinting) Resource->AddStamina(-DeltaTime);
	if (IsStaminaRecovering) Resource->AddStamina(DeltaTime * RestoreMultiplier);
}

// Called to bind functionality to input
void AActionCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	UEnhancedInputComponent* enhanced = Cast<UEnhancedInputComponent>(PlayerInputComponent);

	if (enhanced) // 입력 컴포넌트가 향상된 입력 컴포넌트일 때
	{
		enhanced->BindAction(IA_Move, ETriggerEvent::Triggered, this, &AActionCharacter::OnMoveInput);
		enhanced->BindAction(IA_Roll, ETriggerEvent::Triggered, this, &AActionCharacter::OnRollInput);
		enhanced->BindActionValueLambda(IA_Sprint, ETriggerEvent::Started,
			[this](const FInputActionValue& _) {
				SetSprintMode();
			});
		enhanced->BindActionValueLambda(IA_Sprint, ETriggerEvent::Completed,
			[this](const FInputActionValue& _) {
				SetWalkMode();
			});
	}
}

void AActionCharacter::OnMoveInput(const FInputActionValue& InValue)
{
	FVector2D InputDirection = InValue.Get<FVector2D>();

	//UE_LOG(LogTemp, Log, TEXT("Dir : (%.1f, %.1f)"), InputDirection.X, InputDirection.Y);
	//UE_LOG(LogTemp, Log, TEXT("Dir : (%s)"), *InputDirection.ToString());

	FVector moveDirection(InputDirection.Y, InputDirection.X, 0.0f);

	FQuat controlYawRotation = FQuat(FRotator(0, GetControlRotation().Yaw, 0)); // 컨트롤러의 Yaw 회전을 따로 뽑아와서
	moveDirection = controlYawRotation.RotateVector(moveDirection); // 이동 방향에 적용

	AddMovementInput(moveDirection);
}

void AActionCharacter::OnRollInput(const FInputActionValue& InValue)
{
	if (AnimInstance.IsValid())
	{
		if (!AnimInstance->IsAnyMontagePlaying() && Resource->HasEnoughStamina(RollStamina))
		{
			IsStaminaRecovering = false;
			//SetActorRotation(GetLastMovementInputVector().Rotation());
			Resource->AddStamina(-RollStamina);
			PlayAnimMontage(RollMontage);
			DelayStaminaRestore();
		}
	}
}

void AActionCharacter::SetSprintMode()
{
	//UE_LOG(LogTemp, Log, TEXT("달리기 모드"));

	if (!GetVelocity().IsNearlyZero() && !AnimInstance->IsAnyMontagePlaying())
	{
		IsSprinting = true;
		IsStaminaRecovering = false;

		GetCharacterMovement()->MaxWalkSpeed = SprintSpeed;
	}
}

void AActionCharacter::SetWalkMode()
{
	//UE_LOG(LogTemp, Log, TEXT("걷기 모드"));
	if (IsSprinting)
	{
		IsSprinting = false;
		GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
		DelayStaminaRestore();
	}
}

//void AActionCharacter::DelayStaminaRestore()
//{
//	auto& TimerManager = GetWorld()->GetTimerManager();
//	TimerManager.ClearTimer(timerHandle);
//	TimerManager.SetTimer(
//		timerHandle,
//		FTimerDelegate::CreateLambda([this]()
//			{
//				if (!IsSprinting) IsStaminaRecovering = true;
//			}
//		),
//		2.0f,
//		false
//	);
//}

//void AActionCharacter::ManageStamina()
//{
//	GetWorld()->GetTimerManager().SetTimer(
//		StaminaManagerTimerHandle,
//		FTimerDelegate::CreateLambda([this]()
//			{
//			}
//		),
//		StaminaManagerSpeed,
//		true
//	);
//}
